language: c

sudo: false

addons:
  apt:
    packages:
    - libmysqlclient-dev

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    # - LUA=lua5.2
    # - LUA=lua5.3
    # - LUA=luajit     # latest stable version (2.0.3)
    # - LUA=luajit2.0  # current head of 2.0 branch
    # - LUA=luajit2.1  # current head of 2.1 branch


before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luasql-mysql

install:
  - luarocks make rockspecs/sailor-0.5-1.rockspec

script:
  - cd test/dev-app
  - sailor test --verbose

notifications:
  email:
    on_success: change
    on_failure: always
